// REDUX ACTION TYPES
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILED='LOGIN_FAILED'

export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
export const LOGOUT_FAILED='LOGOUT_FAILED'

export const CREATE_USER_SUCCESS='CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED='CREATE_USER_FAILED'