// REDUX ACTION TYPES
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'

export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILED='LOGIN_FAILED'

export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
export const LOGOUT_FAILED='LOGOUT_FAILED'
